"""
Maps abbreviations/codes from SportsPredict API to standard names.
Add new ones as you see them in the API.
"""

ALIASES = {
    # 3-letter codes
    "irn": "iran",
    "ir iran": "iran",
    'ir':'iran',
    "nzl": "new zealand",
    "bra": "brazil",
    "arg": "argentina",
    "fra": "france",
    "ger": "germany",
    "esp": "spain",
    "eng": "england",
    "ita": "italy",
    "por": "portugal",
    "ned": "netherlands",
    "bel": "belgium",
    "cro": "croatia",
    "sui": "switzerland",
    "den": "denmark",
    "aut": "austria",
    "swe": "sweden",
    "nor": "norway",
    "pol": "poland",
    "srb": "serbia",
    "ukr": "ukraine",
    "tur": "turkey",
    "cze": "czech republic",
    "sco": "scotland",
    "wal": "wales",
    "hun": "hungary",
    "gre": "greece",
    "rom": "romania",
    "rou": "romania",
    "svk": "slovakia",
    "fin": "finland",
    "isl": "iceland",
    "irl": "ireland",
    "bih": "bosnia and herzegovina",
    "alb": "albania",
    "mkd": "north macedonia",
    "mne": "montenegro",
    "svn": "slovenia",
    "geo": "georgia",
    "arm": "armenia",
    "aze": "azerbaijan",
    "kos": "kosovo",
    "blr": "belarus",
    "lux": "luxembourg",
    "bul": "bulgaria",
    "bgr": "bulgaria",
    "isr": "israel",
    "est": "estonia",
    "lva": "latvia",
    "ltu": "lithuania",
    "cyp": "cyprus",
    "fro": "faroe islands",
    "mlt": "malta",
    "gib": "gibraltar",
    "lie": "liechtenstein",
    "and": "andorra",
    "smr": "san marino",
    "mda": "moldova",
    "kaz": "kazakhstan",
    # CONMEBOL
    "uru": "uruguay",
    "col": "colombia",
    "chi": "chile",
    "ecu": "ecuador",
    "per": "peru",
    "par": "paraguay",
    "ven": "venezuela",
    "bol": "bolivia",
    # CAF
    "mar": "morocco",
    "sen": "senegal",
    "nga": "nigeria",
    "egy": "egypt",
    "cmr": "cameroon",
    "civ": "ivory coast",
    "alg": "algeria",
    "tun": "tunisia",
    "gha": "ghana",
    "mli": "mali",
    "rsa": "south africa",
    "cod": "dr congo",
    "bfa": "burkina faso",
    "gui": "guinea",
    "cpv": "cape verde",
    "gab": "gabon",
    "ben": "benin",
    "moz": "mozambique",
    "zam": "zambia",
    "zim": "zimbabwe",
    "uga": "uganda",
    "tan": "tanzania",
    "ken": "kenya",
    "mad": "madagascar",
    "sdn": "sudan",
    "lby": "libya",
    "eqg": "equatorial guinea",
    "nam": "namibia",
    "tog": "togo",
    "rwa": "rwanda",
    "ang": "angola",
    "cgo": "congo",
    "nig": "niger",
    "sle": "sierra leone",
    "mtn": "mauritania",
    "eth": "ethiopia",
    "bot": "botswana",
    "com": "comoros",
    "gam": "gambia",
    "mwi": "malawi",
    "les": "lesotho",
    "swz": "eswatini",
    "lbr": "liberia",
    "gnb": "guinea-bissau",
    "cha": "chad",
    "bdi": "burundi",
    "ssd": "south sudan",
    "eri": "eritrea",
    "dji": "djibouti",
    "som": "somalia",
    # AFC
    "jpn": "japan",
    "kor": "south korea",
    "aus": "australia",
    "ksa": "saudi arabia",
    "qat": "qatar",
    "irq": "iraq",
    "uae": "uae",
    "uzb": "uzbekistan",
    "chn": "china",
    "omn": "oman",
    "bhr": "bahrain",
    "jor": "jordan",
    "syr": "syria",
    "vie": "vietnam",
    "tha": "thailand",
    "ind": "india",
    "idn": "indonesia",
    "ple": "palestine",
    "kgz": "kyrgyzstan",
    "tjk": "tajikistan",
    "kwt": "kuwait",
    "prk": "north korea",
    "lbn": "lebanon",
    "mas": "malaysia",
    "phi": "philippines",
    # CONCACAF
    "mex": "mexico",
    "usa": "usa",
    "can": "canada",
    "crc": "costa rica",
    "pan": "panama",
    "jam": "jamaica",
    "hon": "honduras",
    "slv": "el salvador",
    "hai": "haiti",
    "tri": "trinidad and tobago",
    "gua": "guatemala",
    "cur": "curacao",
    "nic": "nicaragua",
    "sur": "suriname",
    # OFC
    "nzl": "new zealand",
    "sol": "solomon islands",
    "fij": "fiji",
    "png": "papua new guinea",
    "tah": "tahiti",
    "ncl": "new caledonia",
    "van": "vanuatu",
    "sam": "samoa",
    "tga": "tonga",
    # Alternate names
    "korea republic": "south korea",
    "korea": "south korea",
    "holland": "netherlands",
    "czechia": "czech republic",
    "united states": "usa",
    "cote d'ivoire": "ivory coast",
}


def resolve_team(name):
    """Convert any team name/code to standard lookup name."""
    key = name.lower().strip()
    return ALIASES.get(key, key)